### ISSUE TITLE
pypi publish CI workflow is failing

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/tap-hubspot#69]
@edgarrmondragon or @kgpayne do either of you know whats going on with this? https://github.com/MeltanoLabs/tap-hubspot/actions/runs/7657213847

```
Trusted publishing exchange failure: 
Token request failed: the server refused the request for the following reasons:

* `invalid-publisher`: valid token, but no corresponding publisher (All lookup strategies exhausted)
* ```

**Comment by edgarrmondragon** [comment]
@pnadolny13 I think we first need to rename the project since https://pypi.org/project/tap-hubspot/ already exists: https://github.com/MeltanoLabs/tap-hubspot/pull/70

**Comment by edgarrmondragon** [comment]
https://pypi.org/project/meltano-tap-hubspot/

**Comment by pnadolny13** [comment]
@edgarrmondragon 🚀  thanks for doing that so fast!
