### ISSUE TITLE
ValueError: time data does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

### ISSUE THREAD

**Issue by srpwnd** [MeltanoLabs/tap-hubspot#73]
I'm receiving `ValueError: time data '2024-03-28T09:11:41.829618+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'` errors on some streams and not on others. Namely in my testing this happens on Companies stream but does not happen on Calls stream.

I've done some digging around and the error point to [this line](https://github.com/MeltanoLabs/tap-hubspot/blob/main/tap_hubspot/client.py#L307) where datetime str from state is parsed into datetime object. It uses the `%Y-%m-%dT%H:%M:%S.%fZ` format as mentioned in the error. But I noticed there is a different format in my Companies stream state:

```json
{
"singer_state": {
    "bookmarks": {
        "companies": {
            "replication_key": "hs_lastmodifieddate", 
            "replication_key_value": "2024-03-28T09:11:41.829618+00:00"
        }
    }
}
}
```

This datetime string is in format `%Y-%m-%dT%H:%M:%S.%f%z` and causes issues.

I digged deeper and found [this part](https://github.com/MeltanoLabs/tap-hubspot/blob/main/tap_hubspot/client.py#L225) that sets the data type of the replication key to `DateTimeType` which in [Meltano SDK docs](https://sdk.meltano.com/en/latest/classes/typing/singer_sdk.typing.DateTimeType.html) is referenced to be of same format as my Companies timestamp (which is not the same format that is expected and parsed by this tap).

I'm very much confused why there are multiple different timestamp formats in use and how to prevent that.

Any help is appreciated. I'm happy to make a PR if you point me in the right direction.

**Comment by edgarrmondragon** [comment]
> [Meltano SDK docs](https://sdk.meltano.com/en/latest/classes/typing/singer_sdk.typing.DateTimeType.html) is referenced to be of same format as my Companies timestamp (which is not the same format that is expected and parsed by this tap).

That in particular is just an example of the format validated by the JSON Schema `date-time` keyword, and both `2018-11-13T20:20:39+00:00` and `2018-11-13T20:20:39Z` are valid according to the spec so that's not the root of the problem.

> I'm very much confused why there are multiple different timestamp formats in use and how to prevent that.

I think the issue is that Hubspot sometimes respond with different date-time formats.

I think I have a fix so I'll submit a PR.
