### ISSUE TITLE
Properties field from schema is removed

### ISSUE THREAD

**Issue by tobiascadee** [MeltanoLabs/tap-hubspot#76]
I have a bit of a weird problem. When run this Tap for the deals stream the schema is correctly identifying all properties and all of the properties within the properties field. In the output however this field is removed and I end up with this schema: 

```
{'properties': {'id': {'type': ['string', 'null']}, 'hs_lastmodifieddate': {'format': 'date-time', 'type': ['string', 'null']}}, 'type': 'object'}
```

The `hs_lastmodifieddate` field is the incremental key which is retrieved from the properties field but the rest of those fields are filtered out somewhere. I hope you can help me with this as I cannot seem to find where this filtering takes place.

Thanks in advance!

**Comment by edgarrmondragon** [comment]
Hi @tobiascadee, what does your `meltano.yml` look like?

**Comment by tobiascadee** [comment]
@edgarrmondragon my bad, I had `deals` instead of `deals.*` in the select configuration!
